name: CI / Lint

on:
  schedule:
    - cron: '0 */4 * * *'
  push:
    branches: ['dev', '**']
  pull_request:
    branches: ['dev', '**']
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  auto-fix:
    name: Auto Fix Linter Issues
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install Dependencies
        id: install
        run: npm run setup

      - name: Run Auto Fixer
        run: npm run auto-fix

  lint:
    name: Begin Linting
    runs-on: ubuntu-latest
    needs: [auto-fix]
    continue-on-error: true
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npx pnpm i

      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: dev
          FILTER_REGEX_EXCLUDE: dist/**/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_TYPESCRIPT_STANDARD: false


